### ISSUE TITLE
demo.py stuck at Opening connection on a pi zero w

### ISSUE THREAD

**Issue by Ankush-Pathak** [zafartahirov/fingerpi#19]
The demo.py script is stuck at "Opening connection...".
Also, tried running it with sudo.
Have added "enable_uart=1" at the end of config.txt in /boot/

**Comment by CaolanMcB96** [comment]
hi, 
I too am having this problem

**Comment by Ankush-Pathak** [comment]
Disabling bluetooth by modifying the config.txt in /boot/ resolved the issue for me.

**Comment by CaolanMcB96** [comment]
Could you give me a walkthrough on how to do this as i am relatively new to the Pi?

**Comment by Ankush-Pathak** [comment]
-Do "sudo nano /boot/config.txt" via ssh or by opening a terminal on the pi. 
-Scroll down to the end of the file using arrow keys, on a new line add "dtoverlay=pi3-disable-bt". 
-Then do ctrl + o, return(saves your file), ctrl + x(exits nano). 
-Reboot.
-If this does not work, many people also suggested changing the modes of the required GPIO pins to ALT0 or ALT5. You could try that too.

**Comment by CaolanMcB96** [comment]
Any time i execute the demo.py file now, the terminal window appears for a split second then disappears again now even getting to the stage of "Opening connection..."

**Comment by Ankush-Pathak** [comment]
How do you execute your demo.py?
![image](https://user-images.githubusercontent.com/17806816/36438750-ce572416-1690-11e8-8343-4930cd64fe84.png)
GT511C3 - Pi
1 -------------> 10(BCM 14)
2 -------------> 8(BCM 15)
3 -------------> 6
4 -------------> 1,2 or 4
Pi pin numbers from here - pinout.xyz

**Comment by zafartahirov** [comment]
@Ankush-Pathak Thank you for the description -- I am adding it to the README, if you don't mind.

@CaolanMcB96 

1. There is no such thing as "wrong cables" -- at least not in this context.
2. Also, do not run the `demo.py` -- it is NOT designed to work on every machine! For that purpose, I wrote the `interactive.py`. However, even in the case of the `interactive.py`, it assumes that your hardware setup is correct.

**Comment by CaolanMcB96** [comment]
@zafartahirov @Ankush-Pathak I've attached my current setup, the small Green LED on the sensor is not lighting up so this is what makes me think it's a cable problem, the cables i used were pre crimped however the crimp was too big for the housing, so i cut them down and crudely forced them in (I fear this may be the problem) i have no ordered these cables https://www.amazon.co.uk/Cable-JST-SH-4-20-cm/dp/B00L7YZ0IA

![img_0106](https://user-images.githubusercontent.com/33484891/36456279-047ebe0e-169c-11e8-860a-956d91564646.JPG)

**Comment by caolanmcbride** [comment]
I have gotten the new wires and the green light now is on. When i run interative.py the following error appears 
![interactive py error](https://user-images.githubusercontent.com/25526410/36799060-23784632-1ca4-11e8-8cee-9028e1911700.PNG)

**Comment by Ankush-Pathak** [comment]
Instead of ./ try running it this way "python interactive.py"

**Comment by CaolanMcB96** [comment]
This still gives me the same error.

pi@raspberrypi:~/fingerpi $ python interactive.py
Traceback (most recent call last):
  File "interactive.py", line 8, in <module>
    from gui.interactive import processmenu
  File "/home/pi/fingerpi/gui/interactive.py", line 17, in <module>
    from .menu_data import MENU, COMMAND, EXITMENU # processrequest, 
  File "/home/pi/fingerpi/gui/menu_data.py", line 61, in <module>
    ports = _serial_ports()
  File "/home/pi/fingerpi/gui/menu_data.py", line 54, in _serial_ports
    except (OSError, serial.Exception):
AttributeError: 'module' object has no attribute 'Exception'

**Comment by Ankush-Pathak** [comment]
Try installing pyserial using pip or apt.

**Comment by CaolanMcB96** [comment]
Tired this and its saying that "Requirement already satisfied"

**Comment by CaolanMcB96** [comment]
the demo.py is stuck on "Opening connection" and this is the error that appears when i terminate the program. 

Opening connection...
^CTraceback (most recent call last):
  File "demo.py", line 31, in <module>
    f.Open(extra_info = True, check_baudrate = True)
  File "/home/pi/fingerpi/fingerpi/fingerpi.py", line 74, in Open
    if not self.sendCommand('Open', extra_info):
  File "/home/pi/fingerpi/fingerpi/fingerpi.py", line 43, in sendCommand
    result = len(packet) == self.serial.write(packet)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 542, in write
    abort, ready, _ = select.select([self.pipe_abort_write_r], [self.fd], [], None)
KeyboardInterrupt


Here is the error when i run the interactive.py 

Traceback (most recent call last):
  File "interactive.py", line 8, in <module>
    from gui.interactive import processmenu
  File "/home/pi/fingerpi/gui/interactive.py", line 17, in <module>
    from .menu_data import MENU, COMMAND, EXITMENU # processrequest, 
  File "/home/pi/fingerpi/gui/menu_data.py", line 61, in <module>
    ports = _serial_ports()
  File "/home/pi/fingerpi/gui/menu_data.py", line 54, in _serial_ports
    except (OSError, serial.Exception):
AttributeError: 'module' object has no attribute 'Exception'

**Comment by CaolanMcB96** [comment]
My demo.py file now works and saves a file called "raw_img.pickle" however the interactive.py still displays the same error as above. Would you know why? This is part of my final year project and i need to figure it out ASAP as it is holding other elements of the project back. Thanks @Ankush-Pathak @zafartahirov

**Comment by Ankush-Pathak** [comment]
Why rely on interactive.py, you can write your own code to do things. Take a look at finger.py(/fingerpi/fingerpi). You can find all the functions you need there(start reading from CmosLed). Take demo.py as a reference and write your code, save it in the same directory as demo.py. Simply call the functions defined in finger.py and pass the required parameters. The functions names are also very intuitive.
