### ISSUE TITLE
demo.py issuing same error at different points of the program

### ISSUE THREAD

**Issue by tsarjak** [zafartahirov/fingerpi#20]
While running the demo.py file, I am getting the following error at different times (sometimes while opening port, sometimes while changing baudrate etc)

Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    f.Open(extra_info = False, check_baudrate = False)
  File "/home/pi/Desktop/fingerpi/fingerpi/fingerpi.py", line 88, in Open
    response = self.getResponse()
  File "/home/pi/Desktop/fingerpi/fingerpi/fingerpi.py", line 51, in getResponse
    return decode_command_packet(bytearray(response))
  File "/home/pi/Desktop/fingerpi/fingerpi/base.py", line 103, in decode_command_packet
    raise Exception(str(e) + ' ' + str(packet[0]))
Exception: unpack_from requires a buffer of at least 10 bytes 0

**Comment by zafartahirov** [comment]
`demo.py` is not intended to be run -- it was never tested anywhere except my own setup. Try using the `interactive.py`
