### ISSUE TITLE
EnrollStart Error (unpack requires a string argument of length 10 30)

### ISSUE THREAD

**Issue by ebenezer-isaac** [zafartahirov/fingerpi#28]
I forked your repo and modded it a lot to serve my project needs but I am stuck at this error, can you help me out?
```
from fingerpi.fingerpi import FingerPi
f = FingerPi()
def waitForFinger():
    f.CmosLed(True)
    while not f.IsPressFinger()[0]['Parameter']==0:
        pass
def Enroll(id):
    f.CmosLed(True)
    f.EnrollStart(id)
    print("Place finger..")
    waitForFinger()
    response = f.CaptureFinger(True)
    enr = f.Enroll1()
    print(enr)
    print("remove finger")
    time.sleep(5)
    print("Place same finger again..")
    waitForFinger()
    response = f.CaptureFinger(True)
    enr = f.Enroll2()
    print(enr)
    print("remove finger")
    time.sleep(5)
    print("place same finger again..")
    waitForFinger()
    response = f.CaptureFinger(True)
    enr = f.Enroll3()
    print(enr)
    print("remove finger")
    f.CmosLed(False)
Enroll(1)
```
I get this error:
```
Traceback (most recent call last):
  File "enroll.py", line 31, in <module>
    Enroll(1)
  File "enroll.py", line 9, in Enroll
    f.EnrollStart(id)
  File "/home/pi/fingerpi/fingerpi/fingerpi.py", line 141, in EnrollStart
    return [self.getResponse(), None]
  File "/home/pi/fingerpi/fingerpi/fingerpi.py", line 50, in getResponse
    return decode_command_packet(bytearray(response))
  File "/home/pi/fingerpi/fingerpi/base.py", line 103, in decode_command_packet
    raise Exception(str(e) + ' ' + str(packet[0]))
Exception: unpack requires a string argument of length 10 170

```

@jsn5 The code I am using is part of your code which you posted in another issue, with just the new function waitForFinger() which loops till a finger is pressed. It would be a great help if you could help me out with this

**Comment by ebenezer-isaac** [comment]
I figured out the problem, I forgot to enable UART after formatting raspbian

[https://raspberrypi.stackexchange.com/questions/47671/why-my-program-wont-communicate-through-ttyama0-on-raspbian-jessie]
